[package]
name = "krab-kart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.8"
sdl2 = "0.35.2"

[profile.dev.package."*"]
opt-level=3
